import { Product } from '../types';

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: 'c1',
    slug: 'velvet-rose-candle',
    name: 'Velvet Rose',
    description: 'A rich, opulent candle with deep rose and velvety musk undertones.',
    category: 'candle',
    collection: 'Floral Bouquets',
    price_kobo: 4500000,
    scent_notes: ['Damask Rose', 'Musk', 'Sandalwood'],
    image_url: '/product-lamour.jpg',
    stock: 25,
    featured: true,
  },
  {
    id: 'c-vla',
    slug: 'velvet-lavender-amber-candle',
    name: 'Velvet Lavender & Amber Candle',
    description: 'The signature house candle. Hand-poured organic soy wax infused with soothing French lavender, radiant golden amber, and subtle botanical undertones.',
    category: 'candle',
    collection: 'Warm & Sensual',
    price_kobo: 3500000,
    scent_notes: ['French Lavender', 'Golden Amber', 'Vanilla Bean', 'Smoked Cedar'],
    image_url: '/website-bg.jpg',
    stock: 25,
    featured: true,
  },
  {
    id: 'c-tla',
    slug: 'twilight-lavender-amber-candle',
    name: 'Twilight Lavender & Amber Noir Candle',
    description: 'An evening composition of wild twilight lavender, smoldering dark amber resin, and creamy Tahitian vanilla in a frosted artisan vessel.',
    category: 'candle',
    collection: 'Warm & Sensual',
    price_kobo: 5400000,
    scent_notes: ['Twilight Lavender', 'Dark Amber Resin', 'Tahitian Vanilla', 'Smoked Sandalwood'],
    image_url: '/product-velvet-lavender.jpg',
    stock: 25,
    featured: true,
  },
  {
    id: 'c-vosj',
    slug: 'vanilla-oud-smoked-jasmine-candle',
    name: 'Vanilla Oud & Smoked Jasmine Candle',
    description: 'A seductive blend of smoky night-blooming jasmine, dark agarwood (oud), and Madagascar vanilla bean.',
    category: 'candle',
    collection: 'Exclusive Collection',
    price_kobo: 5800000,
    scent_notes: ['Madagascar Vanilla', 'Dark Agarwood Oud', 'Night Jasmine', 'Smoked Incense'],
    image_url: '/product-vanilla-oud.jpg',
    stock: 20,
    featured: true,
  },
  {
    id: 'c-wrb',
    slug: 'white-rose-bergamot-candle',
    name: 'White Rose & Bergamot Candle',
    description: 'Crisp Italian bergamot infused with delicate Bulgarian white petals, green mandarin, and cashmere wood.',
    category: 'candle',
    collection: 'Floral Bouquets',
    price_kobo: 4600000,
    scent_notes: ['Bulgarian White Rose', 'Italian Bergamot', 'Green Mandarin', 'Cashmere Wood'],
    image_url: '/product-rose-bergamot.jpg',
    stock: 30,
    featured: false,
  },
  {
    id: 'c-snsc',
    slug: 'santal-noir-cardamom-candle',
    name: 'Santal Noir & Cardamom Candle',
    description: 'An exotic medley of Australian sandalwood, roasted Guatemalan cardamom, and black amber resin.',
    category: 'candle',
    collection: 'Warm & Sensual',
    price_kobo: 5200000,
    scent_notes: ['Australian Sandalwood', 'Black Cardamom', 'Tonka Bean', 'Dark Leather'],
    image_url: '/product-vanilla-oud.jpg',
    stock: 18,
    featured: false,
  },
  {
    id: 'p1',
    slug: 'lamour-perfume',
    name: "L'Amour",
    description: 'A captivating floral fragrance that embodies romance and elegance.',
    category: 'perfume',
    collection: 'Floral Bouquets',
    price_kobo: 12800000,
    scent_notes: ['Rose', 'Peony', 'White Musk'],
    image_url: '/product-lamour.jpg',
    stock: 20,
    featured: true,
  },
  {
    id: 'p2',
    slug: 'rose-noir-perfume',
    name: 'Rose Noir',
    description: 'A dark, sophisticated rose with smoky oud and leather accents.',
    category: 'perfume',
    collection: 'Warm & Sensual',
    price_kobo: 15800000,
    scent_notes: ['Dark Rose', 'Oud', 'Leather'],
    image_url: '/product-rose-noir.jpg',
    stock: 15,
    featured: true,
  },
  {
    id: 'p3',
    slug: 'eau-de-lumiere',
    name: 'Eau de Lumière',
    description: 'Radiant and luminous — citrus sparkle meets golden warmth.',
    category: 'perfume',
    collection: 'Fresh & Radiant',
    price_kobo: 12800000,
    scent_notes: ['Bergamot', 'Neroli', 'Amber'],
    image_url: '/product-eau-lumiere.jpg',
    stock: 22,
    featured: true,
  },
  {
    id: 'p4',
    slug: 'jardin-secrete',
    name: 'Jardin Secrète',
    description: 'A hidden garden of white florals and fresh green notes.',
    category: 'perfume',
    collection: 'Fresh & Radiant',
    price_kobo: 11500000,
    scent_notes: ['Lily of Valley', 'Green Fig', 'White Cedar'],
    image_url: '/product-jardin.jpg',
    stock: 28,
    featured: true,
  },
  {
    id: 'p5',
    slug: 'aroma-intense',
    name: 'Aroma Intense',
    description: 'The signature house perfume — bold, rich, and unforgettable.',
    category: 'perfume',
    collection: 'Exclusive Collection',
    price_kobo: 16800000,
    scent_notes: ['Saffron', 'Oud', 'Ambergris'],
    image_url: '/product-intense.jpg',
    stock: 10,
    featured: true,
  },
  {
    id: 'p6',
    slug: 'golden-dusk',
    name: 'Golden Dusk',
    description: 'Sunset captured in a bottle — warm, golden, and irresistible.',
    category: 'perfume',
    collection: 'Exclusive Collection',
    price_kobo: 18500000,
    scent_notes: ['Saffron', 'Oud', 'Ambergris'],
    image_url: '/product-lamour.jpg',
    stock: 14,
    featured: true,
  },
];
